events { }

http {
    server {
        listen 443 ssl;
        server_name d2c97a19-c1ec-45e0-8b79-85d36157a1cc.escritorios.ieselrincon.es;

        ssl_certificate /etc/nginx/fullchain.pem; # YOUR CERT FILE
        ssl_certificate_key /etc/nginx/privkey.pem;  # YOUR KEY FILE

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        include /etc/nginx/mime.types;
    }
}
